// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOB.Data;

#nullable disable

namespace OOB.Data.Migrations
{
    [DbContext(typeof(OOBDbContext))]
    partial class OOBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOB.Data.Entities.ApplicationConfig", b =>
                {
                    b.Property<Guid>("AC_ApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AC_KeyName")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AC_Key")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("AC_Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("AC_ApplicationID", "AC_KeyName", "AC_Key");

                    b.ToTable("ApplicationConfig", (string)null);
                });

            modelBuilder.Entity("OOB.Data.Entities.ProcessingStatus", b =>
                {
                    b.Property<int>("PS_Id")
                        .HasColumnType("int");

                    b.Property<string>("PS_Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("PS_Id");

                    b.ToTable("ProcessingStatus", (string)null);
                });

            modelBuilder.Entity("OOB.Data.Entities.TransactionResponse", b =>
                {
                    b.Property<long>("TR_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TR_Id"));

                    b.Property<int>("PS_Id")
                        .HasColumnType("int");

                    b.Property<string>("TR_Acquirer")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TR_AcquirerCycle")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid>("TR_ApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TR_Command")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR_Mode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<Guid?>("TR_OriginalRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TR_ProcessingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TR_RequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TR_TransactionIndex")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TR_Id");

                    b.HasIndex("PS_Id");

                    b.ToTable("TransactionResponse", (string)null);
                });

            modelBuilder.Entity("OOB.Data.Entities.TransactionResponseNameValue", b =>
                {
                    b.Property<long>("TRNV_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TRNV_Id"));

                    b.Property<string>("TRNV_Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TRNV_Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long>("TR_Id")
                        .HasColumnType("bigint");

                    b.HasKey("TRNV_Id");

                    b.HasIndex("TR_Id");

                    b.ToTable("TransactionResponseNameValue", (string)null);
                });

            modelBuilder.Entity("OOB.Data.Entities.TransactionResponse", b =>
                {
                    b.HasOne("OOB.Data.Entities.ProcessingStatus", "ProcessingStatus")
                        .WithMany("TransactionResponses")
                        .HasForeignKey("PS_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingStatus");
                });

            modelBuilder.Entity("OOB.Data.Entities.TransactionResponseNameValue", b =>
                {
                    b.HasOne("OOB.Data.Entities.TransactionResponse", "TransactionResponse")
                        .WithMany("NameValues")
                        .HasForeignKey("TR_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionResponse");
                });

            modelBuilder.Entity("OOB.Data.Entities.ProcessingStatus", b =>
                {
                    b.Navigation("TransactionResponses");
                });

            modelBuilder.Entity("OOB.Data.Entities.TransactionResponse", b =>
                {
                    b.Navigation("NameValues");
                });
#pragma warning restore 612, 618
        }
    }
}
