name: .NET Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore OOB/OOB.csproj

      - name: Build Project
        run: dotnet build OOB/OOB.csproj --configuration Release --no-restore

      - name: Publish Binaries
        run: dotnet publish OOB/OOB.csproj -c Release -o ./publish --no-build

      - name: Zip Artifacts
        run: zip -r OOBCOnsumer-${{ github.ref_name }}.zip ./publish

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: OOBCOnsumer-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}